Rename `COWMap` to `CopyOnWriteMap` and add javadoc
datafaker-net/datafaker pull request #1207
Opened 2024-05-23 20:49 UTC by snuyanzin

2024-05-23 21:09 UTC, asolntsev requested changes
few typos

2024-05-23 21:09 UTC, asolntsev commented on src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
> + * we don't know which roviders will be used and loading for all takes time.
typo: "roviders"

2024-05-23 21:09 UTC, asolntsev commented on src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
> + * Since it is loaded only once per provider and then is only read then
too many "then"s :)

2024-05-23 21:17 UTC, snuyanzin commented on src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
> + * we don't know which roviders will be used and loading for all takes time.
fixed

2024-05-23 21:18 UTC, snuyanzin commented on src/main/java/net/datafaker/internal/helper/CopyOnWriteMap.java
> + * Since it is loaded only once per provider and then is only read then
let's replace one of them)

2024-05-23 21:22 UTC, asolntsev approved these changes

2024-05-23 22:01 UTC, kingthorin commented
I have a few more tweaks coming for this one. Just need to get in front of a computer. It'll be a few more hours.

2024-05-24 02:08 UTC, kingthorin commented
Sorry I didn't manage it this evening because a school thing went long. I'll tackle it in the morning.

It's just minor tweaks to the Java doc. I think I can do it as a suggestion and just apply it then approve and merge.

2024-05-24 06:33 UTC, snuyanzin commented
Ok, will wait for your response @kingthorin 
currently there is no rush
thanks for looking and willingness to improve it

2024-05-24 08:29 UTC, bodiam commented
@kingthorin @snuyanzin I'll just merge it for now, if it's doc improvements, feel free to send a new PR!

2024-05-24 08:30 UTC, merged

2024-05-24 10:03 UTC, kingthorin commented
Okay no worries. I'll send a new one.