Turkish fields refactored
datafaker-net/datafaker pull request #1389
Opened 2024-10-17 11:51 UTC by senocak

2024-10-17 13:55 UTC, asolntsev requested changes
@senocak All good, but why last name has disappeared?

I cannot find these last names anymore:
>       last_name: [Şen, Kandemir, Çevik, Erkuran, Tüten, Öztürk, Yüzbaşıoğlu, Vural, Yücel, Sönmez, Ertekin, Dede, Uyanık, Aslan, Akbulut, Orhon, Uz, Yavuz, Erdem, Kulaç, Kaya, Selvi, Akpınar, Abacıoğlu, Çay, Işık, Özer, Tahtacı, Büyükcam, Kulaksız, Aksel, Eroğlu, Karakum, Dal, Öcal, Ayhan, Yarbil, Canacankatan, Gümüşay, Murt, Halhallı, Uluöz, Şeyhanlı, Çalışkantürk, Yılmaz, Saraçoğlu, Sezer, Demir, Kayayurt, Sürüm, Yavaşi, Turgut, Tanrıkulu, Barbaros, Aldinç, Tekin, Gülşan, Küfeciler, Almacıoğlu, Çildir, Türkdoğan, Öner, Şeliman, Yaman, Atik, Giray, Yalçınkaya, Kılıç, Şentürk, Karabağ, Değirmenci, Boduroğlu, Yıldız, Güler, Eraslan, Üzer, Pişirgen, Adanır, Koç, Korkmaz, Yenidoğan, Aydoğan, Acarbulut, Erge, Erdoğan, Öğüt, Kuşku, Pektaş, Kayacan, Gülen, Akküçük, Candan, Temel, Yenigün, Yıldırım]

2024-10-18 07:02 UTC, senocak commented
> @senocak All good, but why last name has disappeared?
> 
> I cannot find these last names anymore:
> 
> > ```
> >   last_name: [Şen, Kandemir, Çevik, Erkuran, Tüten, Öztürk, Yüzbaşıoğlu, Vural, Yücel, Sönmez, Ertekin, Dede, Uyanık, Aslan, Akbulut, Orhon, Uz, Yavuz, Erdem, Kulaç, Kaya, Selvi, Akpınar, Abacıoğlu, Çay, Işık, Özer, Tahtacı, Büyükcam, Kulaksız, Aksel, Eroğlu, Karakum, Dal, Öcal, Ayhan, Yarbil, Canacankatan, Gümüşay, Murt, Halhallı, Uluöz, Şeyhanlı, Çalışkantürk, Yılmaz, Saraçoğlu, Sezer, Demir, Kayayurt, Sürüm, Yavaşi, Turgut, Tanrıkulu, Barbaros, Aldinç, Tekin, Gülşan, Küfeciler, Almacıoğlu, Çildir, Türkdoğan, Öner, Şeliman, Yaman, Atik, Giray, Yalçınkaya, Kılıç, Şentürk, Karabağ, Değirmenci, Boduroğlu, Yıldız, Güler, Eraslan, Üzer, Pişirgen, Adanır, Koç, Korkmaz, Yenidoğan, Aydoğan, Acarbulut, Erge, Erdoğan, Öğüt, Kuşku, Pektaş, Kayacan, Gülen, Akküçük, Candan, Temel, Yenigün, Yıldırım]
> > ```

I've missed that 

> @senocak All good, but why last name has disappeared?
> 
> I cannot find these last names anymore:
> 
> > ```
> >   last_name: [Şen, Kandemir, Çevik, Erkuran, Tüten, Öztürk, Yüzbaşıoğlu, Vural, Yücel, Sönmez, Ertekin, Dede, Uyanık, Aslan, Akbulut, Orhon, Uz, Yavuz, Erdem, Kulaç, Kaya, Selvi, Akpınar, Abacıoğlu, Çay, Işık, Özer, Tahtacı, Büyükcam, Kulaksız, Aksel, Eroğlu, Karakum, Dal, Öcal, Ayhan, Yarbil, Canacankatan, Gümüşay, Murt, Halhallı, Uluöz, Şeyhanlı, Çalışkantürk, Yılmaz, Saraçoğlu, Sezer, Demir, Kayayurt, Sürüm, Yavaşi, Turgut, Tanrıkulu, Barbaros, Aldinç, Tekin, Gülşan, Küfeciler, Almacıoğlu, Çildir, Türkdoğan, Öner, Şeliman, Yaman, Atik, Giray, Yalçınkaya, Kılıç, Şentürk, Karabağ, Değirmenci, Boduroğlu, Yıldız, Güler, Eraslan, Üzer, Pişirgen, Adanır, Koç, Korkmaz, Yenidoğan, Aydoğan, Acarbulut, Erge, Erdoğan, Öğüt, Kuşku, Pektaş, Kayacan, Gülen, Akküçük, Candan, Temel, Yenigün, Yıldırım]
> > ```
Yes, you are right. I accidentally deleted it and put them back.

2024-10-18 12:00 UTC, asolntsev approved these changes

2024-10-18 12:05 UTC, kingthorin commented on src/main/resources/tr.yml
> +      suffix: []
This seems to be the cause of the build failure:\08:18:53.700 [ERROR] Errors: 
```
08:18:53.701 [ERROR]   FakerIntegrationTest.testAllFakerMethodsThatReturnStrings:100->testAllMethodsThatReturnStringsActuallyReturnStrings:122 Runtime Test for method public java.lang.String net.datafaker.providers.base.Name.suffix() and object Name(Faker@4b511ea8)@12ace6f4 was failed for locale tr [thread: FakerIntegrationTest.testAllFakerMethodsThatReturnStrings#16902#]
08:18:53.701 [ERROR] Tests run: 19451, Failures: 0, Errors: 1, Skipped: 0
```

2024-10-18 20:24 UTC, senocak commented on src/main/resources/tr.yml
> +      suffix: []
Empty suffix was causing an exception. Removed that. (I'll take a look that later.)

2024-10-18 20:58 UTC, kingthorin approved these changes

2024-10-18 20:58 UTC, merged