fix: University tests
datafaker-net/datafaker pull request #1411
Opened 2024-10-27 16:29 UTC by kingthorin

Extended the expected regex to include a few characters with accents.

Addresses https://github.com/datafaker-net/datafaker/pull/1404#issuecomment-2436479028

Add recently introduced test artifact `test.txt` to `.gitignore`

FYI if anyone needs to run single UnitTest classes or methods locally you can use:
` ./mvnw test -Dtest=UniversityTest`
` ./mvnw test -Dtest=UniversityTest#testName`
syntax.

2024-10-27 18:57 UTC, asolntsev requested changes
1. Why it's needed to ignore file "test.txt"? I don't see any tests that would create such a file.
2. This regex is not enough. UniversityTest still can fail:
```java
java.lang.AssertionError: 
Expecting actual:
  "North Leffler Academy of Aix-Marseille"
to match pattern:
  "[A-Za-z'() öèü]+"
```

2024-10-27 20:55 UTC, kingthorin commented
Oops thanks, I didn’t account for hyphen or other chars, I had searched non-ASCII.

I’ll dig into the test.txt thing, maybe it was something I’d polluted the repo with somehow.

2024-10-27 21:09 UTC, kingthorin commented
@asolntsev fixed.

2024-10-28 05:19 UTC, asolntsev approved these changes

2024-10-28 07:13 UTC, merged